name: libri

services:
  app:
    build:
      context: .
      dockerfile: infra/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - path: .env
        required: false
    volumes:
      - data:/app/data

volumes:
  data:
